### PR TITLE
Setup GitHub Actions to update the add-on reports automatically

### LINKED ISSUE #1: Update the add-on reports automatically
@jobisoft - Consider setting up GitHub Actions to update these add-on reports automatically. TB add-on developers would then get more frequent updates and you would have more time to add new MailExtension APIs... 😉

It looks like GitHub Actions is [already being used](https://github.com/thundernest/thundernest.github.io/actions) to build and deploy the pages, so you would just need to additionally use it to generate and commit the updated reports. GitHub Actions supports automatically running [on a schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule), so it should be trivial to setup. I believe the underlining ATN data is only updated weekly, but you could config it to update the reports daily or even more frequently if necessary. Hope that helps.

BTW, as a TB add-on developer myself, these add-on reports are very interesting and useful. Thanks for maintaining them!

### PR DESCRIPTION
**Pull request by tdulcet**
* Setup GitHub Actions to update the add-on reports automatically. Fixes #1
  * This will automatically update the add-on reports everyday at around noon (12:00) UTC.
  * The commits will be attributed to you (@jobisoft). Please let me know if you would prefer a different time or a different commit message.
* Setup [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) to update the dependencies.
  * This will automatically create PRs when needed to update both the new GitHub Action and existing NPM dependencies.
  * It looks like a couple of the NPM packages are currently outdated, so merging this should trigger a new PR from Dependabot.

### CODE REVIEW

**Comment by tdulcet** [comment]
@jobisoft - GitHub Actions ran automatically on my fork today at the scheduled time, but the `build_reports.js` script failed with these errors:

```
Generating reports...
  -> tb115-expected-compatible
Error, xpilib data missing: emojiaddin
Error, xpilib data missing: attach-from-clipboard
Error, xpilib data missing: header-tools-lite
Error, xpilib data missing: changequote
Error, xpilib data missing: mark-all-read-we
Error, xpilib data missing: sieve
Error, xpilib data missing: checkbox-column
Error, xpilib data missing: gantt-view
Error, xpilib data missing: senderaddresscolumn
Error, xpilib data missing: globalchromecss
Error, xpilib data missing: mailtabs-example
Error, xpilib data missing: downloadstudio-firefox-integra
Error, xpilib data missing: one-click-search
Error, xpilib data missing: mr-tech-disable-xpi-install-de
```
 
There were also several errors like this during the download:
```
Error in getExtensionFiles() for emojiaddin [Error: EACCES: permission denied, mkdir '/home/runner/work/thundernest.github.io/thundernest.github.io/add-on-reports-generator/data/downloads/708783-emojiaddin/2478211/src/chrome/content/'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/home/runner/work/thundernest.github.io/thundernest.github.io/add-on-reports-generator/data/downloads/708783-emojiaddin/2478211/src/chrome/content/'
    Requesting version page: 1
}
```
and other errors that seem to indicate an error with ATN itself:
```
Error in getExtensionFiles() for globalchromecss GotError [HTTPError]: Response code 502 (Bad Gateway)
    Getting files for alwaysdefaultclient@clear-code.com (1088/1687)
    at EventEmitter.<anonymous> (/home/runner/work/thundernest.github.io/thundernest.github.io/add-on-reports-generator/node_modules/got/index.js:482:24)
    at EventEmitter.emit (node:events:517:28)
    at getResponse (/home/runner/work/thundernest.github.io/thundernest.github.io/add-on-reports-generator/node_modules/got/index.js:320:5)
    at Immediate.<anonymous> (/home/runner/work/thundernest.github.io/thundernest.github.io/add-on-reports-generator/node_modules/got/index.js:147:6)
    Requesting version page: 1
    at process.processImmediate (node:internal/timers:476:21) {
  host: 'addons.thunderbird.net',
  hostname: 'addons.thunderbird.net',
  method: 'GET',
  path: '/thunderbird/downloads/file/344912/globalchromecss-1.3-tb+fx.xpi?src=',
  protocol: 'https:',
  url: 'https://addons.thunderbird.net/thunderbird/downloads/file/344912/globalchromecss-1.3-tb+fx.xpi?src=',
  statusCode: 502,
  statusMessage: 'Bad Gateway',
  headers: {
    date: 'Sun, 24 Dec 2023 12:48:21 GMT',
    'content-type': 'text/plain; charset=UTF-8',
    'content-length': '15',
    connection: 'close',
    'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=Ut6NiSl4%2BBEqEIAAZODIFbAOkBRju9fiOYgq8I2Jsz8nyP78afdn5RPIlCurG9n%2Be7Xh3h6iSvo2ANZ5NoQ2OC1d6zyAJ1yRtkvPp6Iw04DoqV7XBcC6LZJBap0YvQL8Q6IvymrMZY8%3D"}],"group":"cf-nel","max_age":604800}',
    nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
    vary: 'Accept-Encoding',
    'x-frame-options': 'SAMEORIGIN',
    'referrer-policy': 'same-origin',
    'cache-control': 'private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
    expires: 'Thu, 01 Jan 1970 00:00:01 GMT',
    server: 'cloudflare',
    'cf-ray': '83a8f5445bdb387a-IAD',
    'alt-svc': 'h3=":443"; ma=86400'
  }
}
```
 
See the full log here: https://github.com/tdulcet/thundernest.github.io/actions/runs/7314531546/job/19927274031
 
It looks like GitHub Actions is using Node.js v18 by default (the latest LTS release), which might be newer than what you were using locally. If this is the case and this is what is causing the error, I could configure it to use an older version, but I suspect you would want to fix this issue anyway... It also could be that some of the dependencies need to be updated for Node.js v18 compatibility.

**Edit**: The new Bugzilla contribution report fails with this exception:
```
/home/runner/work/thundernest.github.io/thundernest.github.io/bugzilla-contribution-generator/node_modules/bent/src/nodejs.js:133
        return reject(new StatusError(res))
                      ^

StatusError: Too Many Requests
    at ClientRequest.<anonymous> (/home/runner/work/thundernest.github.io/thundernest.github.io/bugzilla-contribution-generator/node_modules/bent/src/nodejs.js:133:23)
    at Object.onceWrapper (node:events:632:26)
    at ClientRequest.emit (node:events:517:28)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:541:22)
    at TLSSocket.emit (node:events:517:28)
    at addChunk (node:internal/streams/readable:368:12)
    at readableAddChunk (node:internal/streams/readable:341:9)
    at Readable.push (node:internal/streams/readable:278:10) {
  statusCode: 429,
  json: [AsyncFunction (anonymous)],
  text: [Function (anonymous)],
  arrayBuffer: [Function (anonymous)],
  headers: {
    'content-length': '142',
    'content-type': 'text/html; charset=UTF-8',
    date: 'Sun, 24 Dec 2023 12:30:19 GMT',
    'alt-svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000',
    connection: 'close'
  }
}
```
See the full log here: https://github.com/tdulcet/thundernest.github.io/actions/runs/7314531546/job/19927274134

**Comment by jobisoft** [comment]
I will update to node v18 locally and see what happens/fix the code.

**Comment by tdulcet** [comment]
If you tell me what version of Node.js you are using locally (`node --version`), I could update this PR to temporarily hardcode that version until you have a chance to make the code compatible with Node.js v18.

**Comment by tdulcet** [comment]
@jobisoft - I rebased this PR to include the latest changes from the main branch and then reenabled GitHub Actions to automatically run at the scheduled time. The exception seems to have gone away and the add-on reports now correctly build. There are still those above mentioned errors effecting 14 of the add-ons, but they are not fatal and I am guessing that they probably happen for you locally as well. Those `[HTTPError]: Response code 502 (Bad Gateway)` errors likely could be worked around by just retrying the requests, as this seems to be an intermittent issue with ATN. See https://github.com/thunderbird/addons-server/issues/209.

I also updated the PR to automatically update the new Bugzilla contribution report as well. That fails with a `StatusError: Too Many Requests` exception, but presumably this could easily be fixed by making the requests to BMO a little slower to not hit their rate limit.

For reference, I updated my above comment with the latest copy of all the errors.

**Comment by jobisoft** [comment]
It turns out that each update requires manual work to the files it is generated from, and does not depend only on the updated ATN data. An auto update could then produce false reports, which I do not want to have risc.

Thanks for your effort!

**Comment by tdulcet** [comment]
We could instead push the changes to a separate branch, which would allow you to review them and make any needed manual fixes before merging them with the main branch, which would then update the website. This would still presumably save you time and allow for more frequent updates of the reports.

**Comment by jobisoft** [comment]
After moving the reports out of here into their own repo, I also did the work needed for automatic updates:
- implement a github-action-compatible cache to re-use information generated in previous runs
- remove hardcoded versions and instead pull recent versions from `https://product-details.mozilla.org/1.0/` (which I learned of through your metric scripts)
- reduce amount of stored/cached data

It will download all XPIs on a freshly cloned repo. If the file `data.json` is present, it will only download XPIs whose information is not yet known:

* https://github.com/thunderbird/webext-reports/releases/tag/v1.0.0
* https://github.com/thunderbird/webext-reports/blob/main/.github/workflows/update.yml


It runs every day at least once, time may change. For additional processing, the following JSON file is generated (the next release of the [compatibility test add-on](https://github.com/user-attachments/files/20023599/compatibility_test_addon_2_2.zip) will use it):

* https://github.com/thunderbird/webext-reports/blob/main/docs/all.json

FYI: The ATN flag `experimental` is not referring to `WebExtension Experiments`, but if an add-on is flagged as experimental (it will have a yellow instead of a green button on ATN). Readers of your metrics may be confused.

**Comment by jobisoft** [comment]
The correct public link to the json is

https://thunderbird.github.io/webext-reports/all.json

I think it is behind some sort of CDN and better for automated downloads.

**Comment by tdulcet** [comment]
Thank you for adding the automatic updates. That should be a huge improvement for the community going forward and hopefully save you some time.

I am glad my ATN metric script was able to help with the improvements. The documentation for that product details API is available here: https://wiki.mozilla.org/Release_Management/Product_details. I used your script to help determine how to correctly use the ATN API and parse the compatibility versions.

Thanks for the feedback on my TB metrics. I will change the output from "Experimental Extensions" to "Marked Experimental" to hopefully make that clearer, as well as add a warning emoji. I could also add a footnote, if you believe it needs additional clarification. For reference, here is the updated table:

Type                   | Count
---------------------- | ------------------------
⚠️ Marked Experimental | 378 / 1,804 (20.9534%)
📜 Open Source          | 1,381 / 1,804 (76.5521%)
❤️ Requests donations  | 192 / 1,804 (10.6430%)
💲 Requires payment     | 16 / 1,804 (0.8869%)
📈 Has public stats     | 378 / 1,804 (20.9534%)

Your new JSON data should be very helpful to, for example, provide counts of the WebExtension Experiments without having to download and extract all of the XPI files. I will consider using it in a future version of the TB metrics. My scripts will soon be published here: https://github.com/tdulcet/Thunderbird-Metrics

**Pull request closed without merging**
